### ISSUE TITLE
Update  tailscale snap in snap store.

### ISSUE THREAD

**Issue by arubislander** [canonical/tailscale-snap#3]
Would it be possible to update the tailscale snap in the Snap Store to the latest version in the main branch?

**Comment by samuelallan72** [comment]
This is in progress. We're working with the snap team to obtain approval for publishing the snap with the required interfaces. :)

**Comment by samuelallan72** [comment]
Approval was granted: https://forum.snapcraft.io/t/requesting-interfaces-for-tailscale-snap/44105/10 The revision of the snap from the current main branch is now published to latest/edge. :grin: 🎉

**Comment by arubislander** [comment]
Unfortunately the snap is now only build for amd64 arch, which makes it impossible to install on Ubuntu Touch devices which run on arm64 and armhf). But I will open another issue concerning this.

**Comment by samuelallan72** [comment]
@arubislander thanks for the feedback - we definitely have support for building for other architectures on our backlog. We'll just need to work it into the github workflows. :)

**Comment by arubislander** [comment]
Is there any approximation of a timeline that can be tagged to this? The whole reason I opened this issue was to be able to run a more up to date version of tailscale on my Ubuntu Touch devices. I am sure you can imagine the frustration with having the feeling of having had a part in getting the ball rolling, but to now have all support for the architecture of my devices yanked out from under me for an unspecified length of time.

**Comment by samuelallan72** [comment]
@arubislander I understand the frustration, thanks for your feedback. I'm looking into this right now - it seems it will be simple to re-add arm64 support to our new workflows. Please see https://github.com/canonical/tailscale-snap/pull/30 :) We're hoping to get this released to edge for arm64 as soon as possible.

Unfortunately it might be trickier for armhf, as at this point I don't think we have resources for building on armhf on github runners. We will continue to investigate though.
